swagger-api-info:
  title: Manasbi Chautaari API
  description: Manasbi Chautaari API Swagger Documentation
  version: 0.0.1
  contact-name: Manasbi Parajuli
  contact-url: https://github.com/manasbiparajuli

server:
  error:
    include-message: always
    whitelabel:
      enabled: false
    path: /error

springdoc:
  packages-to-scan: com.manasbi
  paths-to-match: /api/v1/**, /actuator/**
  swagger-ui:
    operations-sorter: alpha
    supported-submit-methods: get
    enabled: true
    path: /api/v1/swagger-ui.html
  show-actuator: true
  writer-with-default-pretty-printer: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: simple

info:
  application:
    name: ${swagger-api-info.title}
    description: Exposes the REST endpoints for the podcast API
    version: 1.0.0

spring:
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: dev, local
server:
  port: 8001

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 8080
